name: Run Train Presence Bot

on: workflow_dispatch

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 30          # підстраховка, можна більше
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_ID:  ${{ secrets.CHAT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - run: pip install --no-cache-dir selenium requests

      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
          install-chromedriver: true

      # keep-alive у фоновому режимі
      - run: while true; do echo "🏓 alive"; sleep 60; done &

      - run: python final_bot_alarm_presence_only.py
